_id: 6107e911258f8d002c124635
name: Detect unused image
description: Detect unused images in your storage
language: javascript
timeout: 120
triggers:
  initialize:
    active: true
    type: http
    options:
      method: Get
      path: /unusedImageDetect
      preflight: true
  cleanAllStorageData:
    active: true
    type: http
    options:
      method: Get
      path: /clean-all-storage-data
      preflight: true
  cleanUnusedStorageData:
    active: true
    type: http
    options:
      method: Get
      path: /clean-unused-storage-data
      preflight: true
env:
  AUTH_APIKEY: "{AUTH_APIKEY}"
