_id: 608bb7901c4a8c002cba4092
title: Match Report
description: Describe your new bucket
icon: receipt
primary: p2p_play
readOnly: false
history: false
properties:
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
    default: :created_at
  p2p_play:
    type: number
    title: p2p_play
    description: Description of the p2p_play input
    options:
      position: bottom
  p2p_play_points_earned:
    type: number
    title: p2p_play_points_earned
    description: Description of the p2p_play_points_earned input
    options:
      position: bottom
  p2m_play:
    type: number
    title: p2m_play
    description: Description of the p2m_play input
    options:
      position: bottom
  p2m_play_points_earned:
    type: number
    title: p2m_play_points_earned
    description: Description of the p2m_play_points_earned input
    options:
      position: bottom
  report_type:
    type: number
    title: report_type
    description: Description of the report_type input
    options:
      position: bottom
    default: 0
  player:
    type: number
    title: player
    description: Description of the player input
    options:
      position: bottom
    default: 0
  play:
    type: number
    title: play
    description: Description of the play input
    options:
      position: bottom
    default: 0
acl:
  write: true==true
  read: true==true
order: 11
category: Reports
