_id: 615191c237f1b4002ddcc260
title: Reward Report
description: Describe your new bucket
icon: receipt
primary: report_type
readOnly: false
history: false
properties:
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
    default: :created_at
  report_type:
    type: number
    title: report_type
    description: Description of the report_type input
    options:
      position: bottom
    default: 0
  status_code:
    type: number
    title: status_code
    description: Description of the status_code input
    options:
      position: bottom
  charge:
    type: number
    title: charge
    description: Description of the charge input
    options:
      position: bottom
    default: 0
  points:
    type: number
    title: points
    description: Description of the points input
    options:
      position: bottom
  charge_ratio:
    type: number
    title: charge_ratio
    description: Description of the charge_ratio input
    options:
      position: bottom
    default: 0
  points_ratio:
    type: number
    title: points_ratio
    description: Description of the points_ratio input
    options:
      position: bottom
    default: 0
acl:
  write: true==true
  read: true==true
order: 11
category: Reports
