_id: 60d9c96d38158a002c3924f5
name: User Rank Index
description: Finds user rank with devkit/database
language: javascript
timeout: 65
triggers:
  getUserRank:
    options:
      method: Get
      path: /userrank
      preflight: true
    type: http
    active: true
  getLeaderUsers:
    options:
      method: Get
      path: /getLeaderUsers
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 24
category: Game
