_id: 617034dfbf2eef002e9cd786
name: Draw Functions
language: javascript
timeout: 61.7
triggers:
  sendChargeRequest:
    options:
      collection: bucket_60ab7235c03a2d002eb2f574
      type: INSERT
    type: database
    active: false
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 15
category: D_1
