_id: 65968b4a073c73002bdb9a6b
title: SMS Log
description: Describe your new bucket
icon: view_stream
primary: msisdn
readOnly: false
history: false
properties:
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
  message:
    type: textarea
    title: message
    description: Description of the message input
    options:
      position: bottom
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  response:
    type: textarea
    title: response
    description: Description of the response input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 26
