_id: 60f16c6f29eb79002d0857de
name: Export Excel
description: Export data as xls or csv format
language: javascript
timeout: 119
triggers:
  initialize:
    active: true
    type: http
    options:
      method: Get
      path: /initializeExportExcel
      preflight: true
  excelExport:
    active: true
    type: http
    options:
      method: Get
      path: /excelExport
      preflight: true
  updateLink:
    options:
      bucket: 60f16c6f29eb79002d0857db
      type: UPDATE
    type: bucket
    active: true
  exportConfrimationCodes:
    options:
      method: Get
      path: /exportConfrimationCodes
      preflight: true
    type: http
    active: false
  exportConfrimationCodesDelete:
    options:
      method: Get
      path: /exportConfrimationCodesDelete
      preflight: true
    type: http
    active: false
  exportDatasManually:
    options:
      method: Get
      path: /exportDatasManually
      preflight: true
    type: http
    active: true
  exportDatasManuallyDelete:
    options:
      method: Get
      path: /exportDatasManuallyDelete
      preflight: true
    type: http
    active: true
env:
  AUTH_APIKEY: "{AUTH_APIKEY}"
  BUCKET_EXPORT_TEMPLATES: "{BUCKET_EXPORT_TEMPLATES}"
  FORMAT_TYPE: "{FORMAT_TYPE}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
