_id: 655b40e8c250ea002c783322
name: Server Environment Variables
language: javascript
timeout: 60
triggers:
  default:
    type: http
    active: false
    options:
      method: Get
      path: /
      preflight: true
env: {}
memoryLimit: 100
order: 11
category: Server
