_id: 633bf949956545002c9b7e31
name: Helper
language: javascript
timeout: 55
triggers:
  replaceAbusiveName:
    type: schedule
    active: true
    options:
      timezone: UTC
      frequency: 0 * * * *
  insertDataWithId:
    options:
      method: Post
      path: /insertDataWithId
      preflight: true
    type: http
    active: true
  getMyIp:
    options:
      method: Get
      path: /getMyIp
      preflight: true
    type: http
    active: true
  createConnection:
    options:
      method: Get
      path: /testTelnet
      preflight: true
    type: http
    active: true
  removeChargeCount:
    options:
      method: Get
      path: /removeChargeCount
      preflight: true
    type: http
    active: false
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 3
category: Helpers
