_id: 60d9c65f38158a002c392492
name: Test Login & Register
description: Test login and register operations
language: javascript
timeout: 73
triggers:
  register:
    options:
      method: Post
      path: /register
      preflight: true
    type: http
    active: true
  login:
    options:
      method: Post
      path: /login
      preflight: true
    type: http
    active: true
env:
  SECRET_API_KEY: "{SECRET_API_KEY}"
  USER_POLICY: "{USER_POLICY}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
memoryLimit: 100
