_id: 60d9c65f38158a002c392492
name: Test Login & Register
description: Test login and register operations
language: javascript
timeout: 73
triggers:
  register:
    options:
      method: Post
      path: /register
      preflight: true
    type: http
    active: true
  login:
    options:
      method: Post
      path: /login
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 0
category: Auth
