_id: 60d9c65f38158a002c392492
name: Test Auth
description: Test login and register operations
language: javascript
timeout: 73
triggers:
  testRegister:
    options:
      method: Post
      path: /test-register
      preflight: true
    type: http
    active: true
  testLogin:
    options:
      method: Post
      path: /test-login
      preflight: true
    type: http
    active: true
  testUserUpdate:
    options:
      method: Post
      path: /test-user-update
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 0
category: Auth
