_id: 65781505c250ea002c7b92cc
title: Contact Message
description: Describe your new bucket
icon: view_stream
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  messages:
    type: array
    title: messages
    description: Description of the messages input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        key:
          type: string
          title: key
          description: Description of the key input
          options:
            position: bottom
        message_date:
          type: date
          title: message_date
          description: Description of the message_date input
          options:
            position: bottom
          default: :created_at
        value:
          type: string
          title: value
          description: Description of the value input
          options:
            position: bottom
  readed:
    type: boolean
    title: readed
    description: Description of the readed input
    options:
      position: bottom
    default: true
  fixed:
    type: boolean
    title: fixed
    description: Description of the fixed input
    options:
      position: bottom
    default: false
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
acl:
  write: true==true
  read: true==true
order: 30
