_id: 616ffbb9bf2eef002e9b4602
title: Draw Participants
description: Describe your new bucket
icon: view_stream
primary: msisdn
readOnly: false
history: false
properties:
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
      translate: false
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  date_of_birth:
    type: date
    title: date_of_birth
    description: Description of the date_of_birth input
    options:
      position: bottom
  address:
    type: textarea
    title: address
    description: Description of the address input
    options:
      position: bottom
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 5
category: DevOps
