_id: 63e11094130d55002c19c79d
name: Server Check Finished Duels
language: javascript
timeout: 6.3
triggers:
  checkFinishedDuels:
    type: schedule
    active: true
    options:
      timezone: UTC
      frequency: "*/10 * * * * *"
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 10
category: Server
