_id: 614dc4c71796e3002e1161ea
title: Retry Report
description: Describe your new bucket
icon: receipt
primary: hourly_retry_false
readOnly: false
history: false
properties:
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
    default: :created_at
  hourly_retry_false:
    type: number
    title: hourly_retry_false
    description: Description of the hourly_retry_false input
    options:
      position: bottom
    default: 0
  hourly_retry_true:
    type: number
    title: hourly_retry_true
    description: Description of the hourly_retry_true input
    options:
      position: bottom
    default: 0
  daily_retry_false:
    type: number
    title: daily_retry_false
    description: Description of the daily_retry_false input
    options:
      position: bottom
    default: 0
  daily_retry_true:
    type: number
    title: daily_retry_true
    description: Description of the daily_retry_true input
    options:
      position: bottom
    default: 0
  report_type:
    type: number
    title: report_type
    description: Description of the report_type input
    options:
      position: bottom
    default: 0
acl:
  write: true==true
  read: true==true
order: 22
