_id: 625d2ea4877d19002c0b5840
title: Draw Logs
description: Describe your new bucket
icon: line_style
primary: msisdn
readOnly: false
history: false
properties:
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
  body:
    type: textarea
    title: body
    description: Description of the body input
    options:
      position: bottom
  response:
    type: textarea
    title: response
    description: Description of the response input
    options:
      position: bottom
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 21
category: Logs
