_id: 611b8c1db157fd002d853f6c
name: In Game
language: javascript
timeout: 60
triggers:
  playCountDecrease:
    type: http
    active: true
    options:
      method: Post
      path: /playCountDecrease
      preflight: true
  changeAvatar:
    options:
      method: Post
      path: /changeAvatar
      preflight: true
    type: http
    active: true
  changeName:
    options:
      method: Post
      path: /changeName
      preflight: true
    type: http
    active: true
  setReadyMainServer:
    options:
      method: Post
      path: /setReadyMainServer
      preflight: true
    type: http
    active: true
  serverInfoUpdate:
    options:
      method: Post
      path: /serverInfoUpdate
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 7
category: D_2
