_id: 607808eba04c51002d25a007
title: Contact Form
description: Contact forms
icon: view_stream
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  email:
    type: string
    title: email
    description: Description of the email input
    options:
      position: bottom
  note:
    type: textarea
    title: note
    description: Description of the note input
    options:
      position: bottom
  about:
    type: string
    title: about
    description: Description of the about input
    options:
      position: bottom
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  read:
    type: boolean
    title: read
    description: Description of the read input
    options:
      position: bottom
    default: false
  fixed:
    type: boolean
    title: fixed
    description: Description of the fixed input
    options:
      position: bottom
    default: false
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  message:
    type: textarea
    title: message
    description: Description of the message input
    options:
      position: bottom
acl:
  write: |-
    auth.attributes.role == "admin" ||
    auth._id == "60f170fa29eb79002d0857e4" || 
    auth._id==document.user.identity
  read: true==true
order: 23
