_id: 60d9c73538158a002c392498
name: Matchmaker
description: This function is working every 5 seconds to match users who are
  looking for a new match.
language: javascript
timeout: 56.5
triggers:
  matchmaker:
    options:
      timezone: Europe/Istanbul
      frequency: "*/5 * * * * *"
    type: schedule
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 11
category: D_1
