_id: 60d9c73538158a002c392498
name: Matchmaker
description: This function is working every 5 seconds to match users who are
  looking for a new match.
language: javascript
timeout: 56.5
triggers:
  matchmaker:
    options:
      timezone: Europe/Istanbul
      frequency: "* * * * *"
    type: schedule
    active: true
  assignDuel:
    options:
      method: Post
      path: /assign-duel
      preflight: true
    type: http
    active: true
  testMessageBroker:
    options:
      method: Get
      path: /testMessageBroker
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 19
category: Game
