_id: 6568680ac250ea002c79844a
name: Reward
language: javascript
timeout: 37
triggers:
  setReward:
    type: schedule
    active: true
    options:
      timezone: UTC
      frequency: "*/5 * * * * *"
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 29
