_id: 63b6d60cebfd83002c5e1966
name: Tcell
language: javascript
timeout: 90
triggers:
  default:
    type: http
    active: false
    options:
      method: Get
      path: /
      preflight: true
env: {}
memoryLimit: 100
order: 26
