_id: 60f1629d29eb79002d085787
name: Dashboards
description: Dashboards function
language: javascript
timeout: 118
triggers:
  matchChart:
    options:
      method: Get
      path: /matchChart
      preflight: true
    type: http
    active: true
  totalMatchChart:
    options:
      method: Get
      path: /totalMatchChart
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 14
category: Operation
