_id: 60d9c90438158a002c3924dd
name: User Point Cleaner
description: Cleans users' weekly points
language: javascript
timeout: 100.1
triggers:
  clearUserPoint:
    options:
      timezone: Europe/Istanbul
      frequency: 0 0 * * 1
    type: schedule
    active: true
  clearBotPoint:
    options:
      timezone: Europe/Istanbul
      frequency: "* * * * *"
    type: schedule
    active: true
  updateConfirmCode:
    options:
      timezone: Europe/Istanbul
      frequency: "* * * * *"
    type: schedule
    active: true
  getLast3MonthsPlayUser:
    options:
      method: Get
      path: /getLast3MonthsPlayUser
      preflight: true
    type: http
    active: false
  setMannualy50KPlayCount:
    options:
      method: Get
      path: /setMannualy50KPlayCount
      preflight: true
    type: http
    active: false
  getDuelsDatas:
    options:
      method: Get
      path: /getDuelsDatas
      preflight: true
    type: http
    active: false
env:
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  CONFIRMATION_CODE_BUCKET_ID: "{CONFIRMATION_CODE_BUCKET_ID}"
memoryLimit: 100
