_id: 60d9c90438158a002c3924dd
name: User Point Cleaner
description: Cleans users' weekly points
language: javascript
timeout: 100.1
triggers:
  clearBotPoint:
    options:
      timezone: Europe/Istanbul
      frequency: "* * * * *"
    type: schedule
    active: true
  setUserPayCount:
    options:
      timezone: Europe/Istanbul
      frequency: 0 0 * * *
    type: schedule
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 22
category: Game
