_id: 60d9d0ed38158a002c392625
name: Alert Function
description: Alert Function
language: javascript
timeout: 62
triggers:
  checkPastMatch:
    options:
      timezone: Europe/Istanbul
      frequency: "* * * * *"
    type: schedule
    active: false
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 15
category: Operation
