_id: 605ca275e9960e002c2781a4
title: Duel
description: The duel between the users
icon: offline_bolt
primary: player_type
readOnly: false
history: false
properties:
  user1:
    type: relation
    title: user1
    description: First user in the duel
    options:
      position: bottom
      index: true
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  user2:
    type: relation
    title: user2
    description: Second User of the duel
    options:
      position: bottom
      index: true
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  user1_ready:
    type: boolean
    title: user1_ready
    description: Checker for the first user is ready or not
    options:
      position: bottom
    default: false
  user2_ready:
    type: boolean
    title: user2_ready
    description: Checker for the first user is ready or not
    options:
      position: bottom
    default: false
  user1_ingame:
    type: boolean
    title: user1_ingame
    description: Description of the user1_ingame input
    options:
      position: bottom
      index: true
    default: false
  user2_ingame:
    type: boolean
    title: user2_ingame
    description: Description of the user2_ingame input
    options:
      position: bottom
      index: true
    default: false
  started_at:
    type: date
    title: started_at
    description: Description of the started_at input
    options:
      position: bottom
  user1_life:
    type: number
    title: user1_life
    description: Description of the user1_life input
    options:
      position: bottom
  user2_life:
    type: number
    title: user2_life
    description: Description of the user2_life input
    options:
      position: bottom
  user1_points:
    type: number
    title: user1_points
    description: Description of the user1_points input
    options:
      position: bottom
    minimum: 0
  user2_points:
    type: number
    title: user2_points
    description: Description of the user2_points input
    options:
      position: bottom
    minimum: 0
  user1_answers:
    type: array
    title: user1_answers
    description: Description of the user1_answers input
    options:
      position: bottom
      index: true
    items:
      title: answer
      type: string
  user2_answers:
    type: array
    title: user2_answers
    description: Description of the user2_answers input
    options:
      position: bottom
      index: true
    items:
      title: answer
      type: string
  is_finished:
    type: boolean
    title: is_finished
    description: Description of the is_finished input
    options:
      position: bottom
    default: false
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  player_type:
    type: number
    title: player_type
    description: Description of the player_type input
    options:
      position: bottom
  winner:
    type: number
    title: winner
    description: Description of the winner input
    options:
      position: bottom
  user1_is_free:
    type: boolean
    title: user1_is_free
    description: Description of the user1_is_free input
    options:
      position: bottom
    default: false
  user2_is_free:
    type: boolean
    title: user2_is_free
    description: Description of the user2_is_free input
    options:
      position: bottom
    default: false
acl:
  write: true==true
  read: true==true
required:
  - user1
  - user2
order: 18
category: Server
