_id: 609669f805b0df002ceb2517
title: Reward Logs
description: Describe your new bucket
icon: line_style
primary: msisdn
readOnly: false
history: false
properties:
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
      index: true
  user_text:
    type: string
    title: user_text
    description: Description of the user_text input
    options:
      position: bottom
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
      index: true
    default: :created_at
  status:
    type: boolean
    title: status
    description: Description of the status input
    options:
      position: bottom
    default: false
  txn_id:
    type: string
    title: txn_id
    description: Description of the txn_id input
    options:
      position: bottom
  status_code:
    type: number
    title: status_code
    description: Description of the status_code input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 16
category: Logs
