_id: 60b616c103f687002c65cf9a
title: Alert
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  message:
    type: textarea
    title: message
    description: Description of the message input
    options:
      position: bottom
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
    default: :created_at
  type:
    type: string
    title: type
    description: Description of the type input
    options:
      position: bottom
    enum:
      - contact
      - system
acl:
  write: true==true
  read: true==true
order: 3
category: DevOps
