_id: 60aa13679835cd002c1c9a1a
title: Manually Reward
description: Whenever you add an entry to bucket, user will get internet reward
icon: line_style
primary: msisdn
readOnly: false
history: false
properties:
  reward:
    type: string
    title: reward
    description: Description of the reward input
    options:
      position: bottom
    enum:
      - weekly_3
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
  purpose:
    type: string
    title: purpose
    description: Description of the purpose input
    options:
      position: bottom
    enum:
      - charge
      - points
acl:
  write: true==true
  read: true==true
order: 16
category: Logs
