_id: 655b108ac250ea002c7831cf
title: Duel Info
description: Describe your new bucket
icon: view_stream
primary: service
readOnly: false
history: false
properties:
  service:
    type: string
    title: service
    description: Description of the service input
    options:
      position: bottom
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  duel_id:
    type: string
    title: duel_id
    description: Description of the duel_id input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 19
category: Server
