_id: 60d9cb8b38158a002c39254d
name: Auth
description: Login & Register with using fastlogin system of Turkcell
language: javascript
timeout: 62
triggers:
  login:
    options:
      method: Post
      path: /login
      preflight: true
    type: http
    active: true
  register:
    options:
      method: Post
      path: /register
      preflight: true
    type: http
    active: true
  userUpdate:
    options:
      method: Post
      path: /user-update
      preflight: true
    type: http
    active: true
  getRedirectURL:
    options:
      method: Get
      path: /getRedirectURL
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 1
category: Auth
