_id: 63e4cd55130d55002c1a49cd
name: BiP Message Service
language: javascript
timeout: 58.1
triggers:
  default:
    type: http
    active: true
    options:
      method: Get
      path: /
      preflight: true
env: {}
memoryLimit: 100
order: 25
