_id: 605c9480e9960e002c278191
title: User
description: User of an app
icon: account_circle
primary: name
readOnly: false
history: false
properties:
  identity:
    type: string
    title: identity
    description: Identity id of an user
    options:
      position: bottom
      index: true
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  perm_accept:
    type: boolean
    title: perm_accept
    description: perm_accept of an user
    options:
      position: bottom
    default: false
  bot:
    type: boolean
    title: bot
    description: if this user is bot or not
    options:
      position: bottom
      index: true
    default: false
  total_point:
    type: number
    title: total_point
    description: Description of the total_point input
    options:
      position: bottom
    default: 0
  range_point:
    type: number
    title: range_point
    description: Description of the range_point input
    options:
      position: bottom
    default: 0
  win_count:
    type: number
    title: win_count
    description: Description of the win_count input
    options:
      position: bottom
    default: 0
  lose_count:
    type: number
    title: lose_count
    description: Description of the lose_count input
    options:
      position: bottom
    default: 0
  free_play:
    type: boolean
    title: free_play
    description: Description of the free_play input
    options:
      position: bottom
    default: false
  available_play_count:
    type: number
    title: available_play_count
    description: Description of the available_play_count input
    options:
      position: bottom
    minimum: 0
    default: 0
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  total_award:
    type: number
    title: total_award
    description: Description of the total_award input
    options:
      position: bottom
    default: 0
    minimum: 0
  range_award:
    type: number
    title: range_award
    description: Description of the range_award input
    options:
      position: bottom
    default: 0
  avatar_id:
    type: number
    title: avatar_id
    description: Description of the avatar_id input
    options:
      position: bottom
    default: 0
  note:
    type: textarea
    title: note
    description: Description of the note input
    options:
      position: bottom
  subscription_status:
    type: string
    title: subscription_status
    description: Description of the subscription_status input
    options:
      position: bottom
    enum:
      - active
      - suspended
      - inactive
      - deactivated
  subscription_start_date:
    type: date
    title: subscription_start_date
    description: Description of the subscription_start_date input
    options:
      position: bottom
  subscription_next_renewal_date:
    type: date
    title: subscription_next_renewal_date
    description: Description of the subscription_next_renewal_date input
    options:
      position: bottom
  subscription_last_renewal_date:
    type: date
    title: subscription_last_renewal_date
    description: Description of the subscription_last_renewal_date input
    options:
      position: bottom
  subscription_end_date:
    type: date
    title: subscription_end_date
    description: Description of the subscription_end_date input
    options:
      position: bottom
  range_reward_count:
    type: number
    title: range_reward_count
    description: Description of the range_reward_count input
    options:
      position: bottom
    default: 0
  op_note:
    type: array
    title: op_note
    description: Description of the op_note input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        date:
          type: date
          title: date
          description: Description of the date input
          options:
            position: bottom
          default: :created_at
        note:
          type: textarea
          title: note
          description: Description of the note input
          options:
            position: bottom
        sender:
          type: string
          title: sender
          description: Description of the sender input
          options:
            position: bottom
acl:
  write: |-
    auth.attributes.role == "admin" ||
    auth.key == "406bus18l2yiufdq" ||
    auth.key == "8rpwp118lp6wqu02" ||
    auth.key == "15roami17lr0oh7wh"
  read: true==true
required: []
order: 21
