_id: 6594096b073c73002bdb0350
title: Subscription Report
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  subscription_created:
    type: number
    title: subscription_created
    description: Description of the subscription_created input
    options:
      position: bottom
    default: 0
  create_subscription_failed:
    type: number
    title: create_subscription_failed
    description: Description of the create_subscription_failed input
    options:
      position: bottom
    default: 0
  subscription_suspended:
    type: number
    title: subscription_suspended
    description: Description of the subscription_suspended input
    options:
      position: bottom
    default: 0
  subscription_resumed:
    type: number
    title: subscription_resumed
    description: Description of the subscription_resumed input
    options:
      position: bottom
    default: 0
  subscription_will_be_deactivated:
    type: number
    title: subscription_will_be_deactivated
    description: Description of the subscription_will_be_deactivated input
    options:
      position: bottom
    default: 0
  subscription_deactivated:
    type: number
    title: subscription_deactivated
    description: Description of the subscription_deactivated input
    options:
      position: bottom
    default: 0
  subscription_deactivation_failed:
    type: number
    title: subscription_deactivation_failed
    description: Description of the subscription_deactivation_failed input
    options:
      position: bottom
    default: 0
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
    default: :created_at
  report_type:
    type: number
    title: report_type
    description: Description of the report_type input
    options:
      position: bottom
    default: 0
  refunded:
    type: number
    title: refunded
    description: Description of the refunded input
    options:
      position: bottom
    default: 0
acl:
  write: true==true
  read: true==true
order: 12
category: Reports
