_id: 658ed34c9b88fb002b2be508
title: Process
description: Describe your new bucket
icon: view_stream
primary: pid
readOnly: false
history: false
properties:
  pid:
    type: number
    title: pid
    description: Description of the pid input
    options:
      position: bottom
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
acl:
  write: true==true
  read: true==true
order: 5
category: DevOps
