_id: 60d9ccfe38158a002c39258c
name: Add Available Play
description: Adds new available play for the user
language: javascript
timeout: 60
triggers:
  addAvailablePlay:
    options:
      method: Post
      path: /add-available-play
      preflight: true
    type: http
    active: true
  checkSMSCode:
    options:
      method: Post
      path: /checkSMSCode
      preflight: true
    type: http
    active: true
  sessionSOAP:
    options:
      method: Post
      path: /sessionSOAP
      preflight: true
    type: http
    active: true
  sendSms:
    options:
      method: Get
      path: /sendSms
      preflight: true
    type: http
    active: true
  charge:
    options:
      method: Post
      path: /charge
      preflight: true
    type: http
    active: true
  getWinner:
    options:
      collection: bucket_60742ed3f95e39002c4917ae
      type: INSERT
    type: database
    active: true
  applyRewardManually:
    options:
      bucket: 60aa13679835cd002c1c9a1a
      type: INSERT
    type: bucket
    active: true
  setPlayAward:
    options:
      method: Post
      path: /setPlayAward
      preflight: true
    type: http
    active: true
  chargeTestMan:
    options:
      method: Get
      path: /chargeTestMan
      preflight: true
    type: http
    active: true
env:
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  JWT_SECRET_KEY: "{JWT_SECRET_KEY}"
  SECRET_API_KEY: "{SECRET_API_KEY}"
  CONFIRMATION_CODE_BUCKET_ID: "{CONFIRMATION_CODE_BUCKET_ID}"
  DUEL_BUCKET_ID: "{DUEL_BUCKET_ID}"
  ALERT_BUCKET_ID: "{ALERT_BUCKET_ID}"
  REWARDS_BUCKET_ID: "{REWARDS_BUCKET_ID}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  BUGGED_REWARDS_BUCKET_ID: "{BUGGED_REWARDS_BUCKET_ID}"
memoryLimit: 100
