_id: 60d9ccfe38158a002c39258c
name: Game Flow Operations
description: Adds new available play for the user
language: javascript
timeout: 60
triggers:
  addAvailablePlayReq:
    options:
      method: Post
      path: /add-available-play
      preflight: true
    type: http
    active: true
  checkSMSCode:
    options:
      method: Post
      path: /checkSMSCode
      preflight: true
    type: http
    active: true
  getWinner:
    options:
      collection: bucket_60742ed3f95e39002c4917ae
      type: INSERT
    type: database
    active: true
  applyRewardManually:
    options:
      bucket: 60aa13679835cd002c1c9a1a
      type: INSERT
    type: bucket
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 11
category: D_2
