_id: 60d9d18838158a002c39263d
name: Mailer API
description: Manages your mail flow automatically
language: javascript
timeout: 50
triggers:
  default:
    options:
      bucket: 60bf26f4c48b36002dd87e01
      type: INSERT
    type: bucket
    active: false
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 15
category: D_1
