_id: 60d9d18838158a002c39263d
name: Mailer API
description: Manages your mail flow automatically
language: javascript
timeout: 50
triggers:
  default:
    options:
      bucket: 60bf26f4c48b36002dd87e01
      type: INSERT
    type: bucket
    active: true
env:
  MAILER_API_KEY: "{MAILER_API_KEY}"
  TEMPLATES_BUCKET_ID: "{TEMPLATES_BUCKET_ID}"
  SMTP_USER: "{SMTP_USER}"
  SMTP_PASSWORD: "{SMTP_PASSWORD}"
  SMTP_HOST: "{SMTP_HOST}"
  MAIL_FROM: "{MAIL_FROM}"
  MATCH_REPORT_BUCKET_ID: "{MATCH_REPORT_BUCKET_ID}"
  CHARGE_REPORT_BUCKET_ID: "{CHARGE_REPORT_BUCKET_ID}"
  USERS_REPORT_BUCKET_ID: "{USERS_REPORT_BUCKET_ID}"
  USERS_MATCH_REPORT_BUCKET_ID: "{USERS_MATCH_REPORT_BUCKET_ID}"
  WIN_LOSE_MATCHES_BUCKET_ID: "{WIN_LOSE_MATCHES_BUCKET_ID}"
  ANSWERS_TO_QUESTION_REPORT_BUCKET_ID: "{ANSWERS_TO_QUESTION_REPORT_BUCKET_ID}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  RETRY_REPORT_BUCKET_ID: "{RETRY_REPORT_BUCKET_ID}"
  REWARD_REPORT_BUCKET_ID: "{REWARD_REPORT_BUCKET_ID}"
memoryLimit: 100
