_id: 60d19214748275002c17ff18
title: Count of Answers To Questions Report
description: Count of Answers To Questions Report
icon: receipt
primary: correct_answer_1
readOnly: false
history: false
properties:
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
    default: :created_at
  correct_answer_1:
    type: number
    title: correct_answer_1
    description: Description of the correct_answer_1 input
    options:
      position: bottom
    default: 0
  correct_answer_2:
    type: number
    title: correct_answer_2
    description: Description of the correct_answer_2 input
    options:
      position: bottom
    default: 0
  correct_answer_3:
    type: number
    title: correct_answer_3
    description: Description of the correct_answer_3 input
    options:
      position: bottom
    default: 0
  wrong_answer_1:
    type: number
    title: wrong_answer_1
    description: Description of the wrong_answer_1 input
    options:
      position: bottom
    default: 0
  wrong_answer_2:
    type: number
    title: wrong_answer_2
    description: Description of the wrong_answer_2 input
    options:
      position: bottom
    default: 0
  wrong_answer_3:
    type: number
    title: wrong_answer_3
    description: Description of the wrong_answer_3 input
    options:
      position: bottom
    default: 0
  report_type:
    type: number
    title: report_type
    description: Description of the report_type input
    options:
      position: bottom
    default: 0
acl:
  write: true==true
  read: true==true
order: 12
category: Reports
