_id: 60eef28ad55625002c3950c8
name: Get Current Date
description: desdes
language: javascript
timeout: 60
triggers:
  testSendMessage:
    options:
      method: Get
      path: /testSendMessage
      preflight: true
    type: http
    active: false
  telnetClient:
    options:
      method: Get
      path: /telnetClient
      preflight: true
    type: http
    active: false
  socketIOTest:
    options:
      method: Get
      path: /testSockedIO
      preflight: true
    type: http
    active: false
  getStartDate:
    options:
      method: Get
      path: /getStartDate
      preflight: true
    type: http
    active: true
env: {}
memoryLimit: 100
order: 4
category: Helpers
