_id: 608a697abce757002c808288
title: Confirmation Codes
description: Describe your new bucket
icon: view_stream
primary: msisdn
readOnly: false
history: false
properties:
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
      index: true
  code:
    type: number
    title: code
    description: Description of the code input
    options:
      position: bottom
  status:
    type: boolean
    title: status
    description: Description of the status input
    options:
      position: bottom
    default: false
  sent_date:
    type: date
    title: sent_date
    description: Description of the sent_date input
    options:
      position: bottom
      index: true
    default: :created_at
  confirmed_date:
    type: date
    title: confirmed_date
    description: Description of the confirmed_date input
    options:
      position: bottom
  is_expired:
    type: boolean
    title: is_expired
    description: Description of the is_expired input
    options:
      position: bottom
      index: true
    default: false
  result:
    type: textarea
    title: result
    description: Description of the result input
    options:
      position: bottom
  result_date:
    type: date
    title: result_date
    description: Description of the result_date input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 25
