_id: 60d9c7f838158a002c3924b0
name: Check Finished Duels
description: This function gets every finished duel and left duels. Then close
  the duel and log everything.
language: javascript
timeout: 56.5
triggers:
  checkFinishedDuels:
    options:
      timezone: Europe/Istanbul
      frequency: "*/10 * * * * *"
    type: schedule
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 13
category: D_1
