_id: 63b57559ebfd83002c5defe5
name: Api
language: javascript
timeout: 53.7
triggers:
  default:
    type: http
    active: true
    options:
      method: Get
      path: /
      preflight: true
env: {}
memoryLimit: 100
order: 2
category: Helpers
