_id: 658d4c059b88fb002b2b7ecf
title: Reward Queue
description: Describe your new bucket
icon: view_stream
primary: msisdn
readOnly: false
history: false
properties:
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  next_try_date:
    type: date
    title: next_try_date
    description: Description of the next_try_date input
    options:
      position: bottom
  last_try_date:
    type: date
    title: last_try_date
    description: Description of the last_try_date input
    options:
      position: bottom
  txn_id:
    type: string
    title: txn_id
    description: Description of the txn_id input
    options:
      position: bottom
  try_count:
    type: number
    title: try_count
    description: Description of the try_count input
    options:
      position: bottom
    default: 0
  purpose:
    type: string
    title: purpose
    description: Description of the purpose input
    options:
      position: bottom
    enum:
      - charge
      - points
acl:
  write: true==true
  read: true==true
order: 25
