_id: 60d9ca5538158a002c392519
name: Add to Match Making
description: Adding user to matchmaking bucket
language: javascript
timeout: 57
triggers:
  addMatchMaking:
    options:
      method: Post
      path: /addMatchMaking
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 22
category: Game
