_id: 656727a0c250ea002c79534d
title: Notification Log
description: Describe your new bucket
icon: view_stream
primary: notification
readOnly: false
history: false
properties:
  notification:
    type: string
    title: notification
    description: Description of the notification input
    options:
      position: bottom
  notification_key:
    type: string
    title: notification_key
    description: Description of the notification_key input
    options:
      position: bottom
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
    default: :created_at
  body:
    type: textarea
    title: body
    description: Description of the body input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 29
