_id: 63e10f77130d55002c19c6f7
name: Server Management
language: javascript
timeout: 51
triggers:
  setReady:
    options:
      method: Post
      path: /setReady
      preflight: true
    type: http
    active: true
  clearScheduler:
    options:
      timezone: UTC
      frequency: "*/5 * * * *"
    type: schedule
    active: true
env:
  DUEL_BUCKET_ID: "{DUEL_BUCKET_ID}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 9
category: Server
