_id: 63e10f77130d55002c19c6f7
name: Server Management
language: javascript
timeout: 51
triggers:
  setReady:
    options:
      method: Post
      path: /setReady
      preflight: true
    type: http
    active: true
  decreasePlayCount:
    options:
      path: /decreasePlayCount
      method: Post
      preflight: true
    type: http
    active: true
  clearIdentity:
    options:
      timezone: UTC
      frequency: "*/5 * * * *"
    type: schedule
    active: true
  updateServerInfo:
    options:
      method: Post
      path: /updateServerInfo
      preflight: true
    type: http
    active: true
env:
  DUEL_BUCKET_ID: "{DUEL_BUCKET_ID}"
  SECRET_API_KEY: "{SECRET_API_KEY}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 4
category: Server
