_id: 60d9d2b438158a002c39266a
name: Retry Reward
description: Retry Reward  Function
language: javascript
timeout: 88
triggers:
  checkReward:
    options:
      timezone: Europe/Istanbul
      frequency: "*/10 * * * *"
    type: schedule
    active: false
  detectUniqueCharges:
    options:
      method: Get
      path: /detectUniqueCharges
      preflight: true
    type: http
    active: false
  detectMissingAvailablePlay:
    options:
      timezone: Europe/Istanbul
      frequency: 0 * * * *
    type: schedule
    active: false
  detectErrorReward:
    options:
      method: Get
      path: /detectErrorReward
      preflight: true
    type: http
    active: false
  detectMissingAvailablePlayTest:
    options:
      method: Get
      path: /detectMissingAvailablePlayTest
      preflight: true
    type: http
    active: false
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 14
category: D_1
