_id: 60d9d2b438158a002c39266a
name: Retry Reward
description: Retry Reward  Function
language: javascript
timeout: 88
triggers:
  checkReward:
    options:
      timezone: Europe/Istanbul
      frequency: "*/10 * * * *"
    type: schedule
    active: false
  retryNonRewardedMatches:
    options:
      method: Get
      path: /retryNonRewardedMatches
      preflight: true
    type: http
    active: false
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 21
category: Game
