_id: 63e11038130d55002c19c75e
name: Check Availability
language: javascript
timeout: 10.8
triggers:
  newGameListener:
    options:
      method: Post
      path: /new-game-listener
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
order: 6
category: Server
