_id: 6067935ee9960e002c27877f
title: Configuration
description: Configuration bucket for changeable metrics
icon: settings_applications
primary: key
readOnly: false
history: false
properties:
  key:
    type: string
    title: key
    description: Description of the key input
    options:
      position: bottom
      unique: true
  value:
    type: string
    title: value
    description: Description of the value input
    options:
      position: bottom
acl:
  write: |-
    auth.attributes.role == "admin" ||
    auth._id == "60f170fa29eb79002d0857e4" || 
    auth.key == "e5wl18kmw287kr"
  read: |-
    auth.attributes.role == "admin" ||
    document.key != "dashboard_key"
required:
  - key
order: 4
