_id: 61c5e60902e67d002f7bbd7b
name: List Dbs
language: javascript
timeout: 90
triggers:
  default:
    type: http
    active: true
    options:
      method: Get
      path: /list-dbs
      preflight: true
env: {}
memoryLimit: 100
