_id: 60ab7235c03a2d002eb2f574
title: Charge Logs
description: Describe your new bucket
icon: line_style
primary: tx_key
readOnly: false
history: false
properties:
  tx_key:
    type: string
    title: tx_key
    description: Description of the tx_key input
    options:
      position: bottom
  msisdn:
    type: string
    title: msisdn
    description: Description of the msisdn input
    options:
      position: bottom
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
  status:
    type: boolean
    title: status
    description: Description of the status input
    options:
      position: bottom
    default: false
  purpose:
    type: string
    title: purpose
    description: Description of the purpose input
    options:
      position: bottom
  amount:
    type: number
    title: amount
    description: Description of the amount input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 14
category: Logs
